export default {
  viewMain: {
    // alignItem:'center',
    // width:'100%',
    // alignSelf:'center',
    backgroundColor: "#ff7070",
    height: 150,
    flex: 1,
    // flexDirection:'row',
    // marginTop:10,
  },
  viewMain_2: {
    // alignItem:'center',
    // width:'100%',
    // alignSelf:'center',
    backgroundColor: "white",
    height: 100,
    // flex:1,
    width: "90%",
    alignSelf: "center",
    marginTop: -40,
    borderRadius: 5,
    height: 570,
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 5,
    shadowOpacity: 0.5,
  },
 
  viewProfile: {
    height: 120,
    // backgroundColor: "#1D85C7",
    marginTop: -40,
    alignSelf:'center',
    flexDirection: "row",
  },
  imageProfile: {
    height: 80,
    width: 80,
    borderRadius: 40,
    backgroundColor: "red",
    resizeMode: "contain",
  },
  txtName: {
    marginTop: 35,
    fontSize: 18,
    fontWeight: "bold",
    // marginLeft:5,
    fontFamily: "NunitoSans-Regular",
  },
  
  imageIcon:{
    height:20,
    width:20,
    marginTop:45,
    marginLeft:-15
  },
    viewInput:{
  // flexDirection:'row',
    marginTop:15,
    width:'90%',
    alignSelf:'center',
},
imageIcon2:{
 height:25,
 width:25,
 resizeMode:'contain',
 marginLeft:20,
 tintColor:'#ff7070',
 // backgroundColor:'red',

},
inputView: {
    flexDirection: "row",   
    alignItems: "center",
    backgroundColor: "white",
    borderWidth: 0.5,
    borderColor: "grey",
    borderRadius:25,
    margin: 10,
    width: '90%',
    height:50, 
    
  },
   textEmail: { 
    marginLeft: 20,
    // fontFamily: "Lato-Regular",
  fontSize: 14,
  color: 'rgb(50,57,86)',
  paddingTop:15,
  paddingBottom:15,
  width:'70%',
  flexWrap:'wrap',
  },
  btnSignIn:{
   height:50,
   backgroundColor:'#ff7070',
   marginTop:50,
   borderRadius:25,
   alignSelf:'center',
   width:"80%",
   alignItem:'center',
   justifyContent:'center',

},
txtSign:{
 textAlign:'center',
 color:'white',
 fontWeight:'500',
 fontSize:15,
},

};
